# Generated by Django 6.1 on 2026-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'کاربران'},
        ),
    ]
