# Generated by Django 6.1 on 2026-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'دسته بندی'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'رنگ '},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name_plural': 'توضیحات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'سایز'},
        ),
    ]
