# Generated by Django 6.1 on 2026-09-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_discount_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name_plural': 'تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'سبد محصولات'},
        ),
    ]
